// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmLv5v9N8JsamoN7JTGOwlXyLYMiWKfBs',
    appId: '1:706039396711:web:cd65e5f9ef4f2aaf3d97c2',
    messagingSenderId: '706039396711',
    projectId: 'test1-f35fc',
    authDomain: 'test1-f35fc.firebaseapp.com',
    storageBucket: 'test1-f35fc.appspot.com',
    measurementId: 'G-W0E5B7XFJY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtlYMnF0IvDd0AGWuu6sLN0XdVJOwEA3Q',
    appId: '1:706039396711:android:6b6a2640adbe51433d97c2',
    messagingSenderId: '706039396711',
    projectId: 'test1-f35fc',
    storageBucket: 'test1-f35fc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFJtXCt16ORSKrRzJU8s1oXCeWD-JFXd4',
    appId: '1:706039396711:ios:4e7ebb3db9ea479c3d97c2',
    messagingSenderId: '706039396711',
    projectId: 'test1-f35fc',
    storageBucket: 'test1-f35fc.appspot.com',
    iosClientId: '706039396711-g773sg056t9h1ifvqkhl687ge57b57e3.apps.googleusercontent.com',
    iosBundleId: 'com.epin.test1',
  );
}
